//! Generates the waybar right-click menu from the installed visualizations,
//! so adding a shader adds a menu entry with no hand-editing.
//!
//! Structure:
//!   Settings…
//!   ───────────────
//!   Off  /  On      ← contextual label (Off when currently off, On otherwise)
//!   Menu bar only
//!   Desktop window only
//!   Menu bar + desktop
//!   ───────────────
//!   Visualizations ▸   ← submenu
//!       Bar: Bars
//!       Bar: Fire
//!       Bar: Wave
//!       …
//!   ───────────────
//!   Fullscreen

use crate::visual;

fn esc(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

fn item(id: &str, label: &str) -> String {
    format!(
        "      <item>\n        <attribute name=\"label\">{label}</attribute>\n        \
         <attribute name=\"action\">win.{id}</attribute>\n      </item>\n",
        label = esc(label)
    )
}

fn submenu(title: &str, items: &str) -> String {
    format!(
        "      <item>\n        <attribute name=\"label\">{title}</attribute>\n        \
         <link name=\"submenu\" type=\"submenu\">\n{items}        </link>\n      </item>\n",
        title = esc(title),
        items = items
    )
}

fn separator() -> String {
    "      <separator/>\n".to_string()
}

/// Returns (GtkBuilder XML, the matching `menu-actions` JSON fragment).
///
/// `current_mode` drives the contextual Off/On label and which mode row is
/// pre-checked (the `win.mode_*` actions also carry a `target` so waybar can
/// tick the active one, but waybar's custom-module menu does not render radio
/// state — we instead preselect by putting a ✓ on the active row).
pub fn generate(current_mode: &str) -> (String, String) {
    let visuals = visual::discover();
    let off = current_mode == "off";

    let mut xml = String::from(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <!-- Generated by `omaviz menu`. Edits will be overwritten. -->\n\
         <interface>\n  <menu id=\"menu\">\n",
    );
    let mut actions: Vec<(String, String)> = Vec::new();

    xml.push_str(&item("settings", "Settings…"));
    actions.push(("settings".into(), "omaviz settings".into()));

    xml.push_str(&separator());

    // Contextual Off/On toggle.
    xml.push_str(&if off {
        item("mode_on", "▶  Turn on")
    } else {
        item("mode_off", "⏸  Turn off")
    });
    if off {
        actions.push(("mode_off".into(), "true".into()));
        actions.push(("mode_on".into(), "omaviz mode mini".into()));
    } else {
        actions.push(("mode_off".into(), "omaviz mode off".into()));
        actions.push(("mode_on".into(), "true".into()));
    }

    // Mode rows, each marked with a ✓ when active.
    let mark = |m: &str| if m == current_mode { "✓ " } else { "" };
    for (id, label, arg) in [
        ("mode_mini", "Menu bar only", "mini"),
        ("mode_desktop", "Desktop window only", "desktop"),
        ("mode_both", "Menu bar + desktop", "mini+desktop"),
    ] {
        xml.push_str(&item(id, &format!("{}{}", mark(arg), label)));
        actions.push((id.into(), format!("omaviz mode {arg}")));
    }

    xml.push_str(&separator());

    // Visualizations submenu (bar-style visuals).
    let mut viz_items = String::new();
    for v in &visuals {
        let id = format!("viz_{}", v.name);
        viz_items.push_str(&item(&id, &format!("Bar: {}", v.display_label())));
        actions.push((id, format!("omaviz select mini {}", v.name)));
    }
    xml.push_str(&submenu("Visualizations", &viz_items));

    xml.push_str(&separator());
    xml.push_str(&item("fullscreen", "Fullscreen"));
    actions.push(("fullscreen".into(), "omaviz full".into()));

    xml.push_str("  </menu>\n</interface>\n");

    let body = actions
        .iter()
        .map(|(k, v)| format!("      \"{k}\": \"{v}\""))
        .collect::<Vec<_>>()
        .join(",\n");
    let actions_json = format!("\"menu-actions\": {{\n{body}\n    }}");

    (xml, actions_json)
}
